
export const CST = {
	SCENES: {
		LOAD: 'LOAD',
		TITLE: 'TITLE',
		GAME: 'GAME',
		SPLITGAME: 'SPLITGAME',
		INFO: 'INFO',
		SPLITINFO: 'SPLITINFO',
		NICKNAME: 'NICKNAME',
		END: 'END',
		SPLITEND: 'SPLITEND',
		TUTO: 'TUTO',
		BONUS: 'BONUS',
		PAUSE: 'PAUSE',
		LEADERBOARD: 'LEADERBOARD'
	}
}